# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: av.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'av.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61v.proto\"\x1e\n\tStreamReq\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"0\n\nStreamResp\x12\x12\n\nlatency_ms\x18\x01 \x01(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t21\n\tAVService\x12$\n\tGetStream\x12\n.StreamReq\x1a\x0b.StreamRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'av_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQ']._serialized_start=12
  _globals['_STREAMREQ']._serialized_end=42
  _globals['_STREAMRESP']._serialized_start=44
  _globals['_STREAMRESP']._serialized_end=92
  _globals['_AVSERVICE']._serialized_start=94
  _globals['_AVSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
